# Generated by Django 4.2.24 on 2025-09-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ROE')),
                ('roa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ROA')),
                ('roic', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ROIC')),
                ('psr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PSR')),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='EV/EBITDA')),
                ('debt_equity_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='D/Eレシオ')),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='流動比率')),
                ('equity_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='自己資本比率')),
                ('asset_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='総資産回転率')),
                ('inventory_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='棚卸回転率')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_indicators', to='stock.stock')),
            ],
        ),
    ]
