# Generated by Django 4.2.24 on 2025-09-27 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_advancedindicator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedindicator',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='advancedindicator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancedindicator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advancedindicator',
            name='date',
            field=models.DateField(verbose_name='取得日'),
        ),
        migrations.AlterUniqueTogether(
            name='advancedindicator',
            unique_together={('stock', 'date')},
        ),
    ]
